### ISSUE TITLE
Launcher GUI Scale

### ISSUE THREAD

**Issue by theotheroracle** [ChristopherHX/mcpelauncher-ui-manifest#9]
Note: This is not a duplicate of  ChristopherHX/mcpelauncher-manifest#95
on my 1920*1080 display, gnome, fedora, the UI of the launcher is scaled to be larger than the entire screen, and it's nearly unusable .

![image](https://user-images.githubusercontent.com/20211219/84579912-9635da00-ad97-11ea-8429-9090d087ba6c.png)

**Comment by ChristopherHX** [comment]
What is qt5.9 (from Appimage) doing on your PC?
Please try running the Appimage like `QT_AUTO_SCREEN_SCALE_FACTOR=0 ./MC.AppImage`, to tell QT5 to not auto scale to 300%. On my PC ubuntu 20.04 gnome 1080p it is only 200% (still large, but not too large for the screen)

**Comment by ChristopherHX** [comment]
Running it with `QT_SCALE_FACTOR=3 QT_AUTO_SCREEN_SCALE_FACTOR=0 ./MC.AppImage`, I get your screenshot.

**Comment by ellietheoracle** [comment]
> Try maximizing it by rightclicking the window bar (temporary but still should work)

firstly, even on other computers, this window does not maximize, even when it's scaled properly, but even if it could be maximized, i still wouldn't fit in the display .

**Comment by theotheroracle** [comment]
> What is qt5.9 (from Appimage) doing on your PC?
> Please try running the Appimage like `QT_AUTO_SCREEN_SCALE_FACTOR=0 ./MC.AppImage`, to tell QT5 to not auto scale to 300%. On my PC ubuntu 20.04 gnome 1080p it is only 200% (still large, but not too large for the screen)

this does fix it though .

**Comment by ChristopherHX** [comment]
The [flatpak](https://flathub.org/apps/details/io.mrarm.mcpelauncher) based on ng (x86_64 only) or my fork (arm only) resolves this issue without the need for a workaround.

Maybe the used ppa of qt5.9 is bugged or the appimage script to assembly the appimage.
Native OS packages doesn't have this bug, I disabled them because of missing update infrastructure (on my side) and reports of errors from older launcher versions.
